[2024-11-06T06:20:58.798+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: my_very_first_dag.my_very_first_task manual__2024-11-06T06:20:54.921598+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
